version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependencies"
      - "bot"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependencies"
      - "bot"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "production"
    labels:
      - "area/dependencies"
      - "bot"
