version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependencies"
      - "bot"

  - package-ecosystem: "gomod"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependencies"
      - "bot"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 0
    directory: "/website"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    labels:
      - "area/dependencies"
      - "bot"
