defaults:
  count: 3
  benchtime: 1s

runs:
  BenchmarkDaemon:
    BenchmarkDaemonVersion:
      description: Run buildkitd --version
      benchtime: 2s
      metrics:
        duration:
          description: Time (s)
    BenchmarkDaemonSize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)

  BenchmarkPackage:
    BenchmarkPackageSize:
      description: Package size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
