defaults:
  count: 3
  benchtime: 1s

runs:
  BenchmarkBuild:
    BenchmarkBuildLocal:
      description: Local build
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildRemoteBuildme:
      description: Remote build of github.com/dvdksn/buildme
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildRemoteBuildx:
      description: Remote build of github.com/docker/buildx
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot

  BenchmarkDaemon:
    BenchmarkDaemonVersion:
      description: Run buildkitd --version
      count: 8
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkDaemonSize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true

  BenchmarkPackage:
    BenchmarkPackageSize:
      description: Package size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true
