defaults:
  count: 3
  benchtime: 1s

runs:
  BenchmarkDaemon:
    BenchmarkDaemonVersion:
      description: Run buildkitd --version
      count: 8
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkDaemonSize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true

  BenchmarkPackage:
    BenchmarkPackageSize:
      description: Package size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true
