defaults:
  count: 3
  benchtime: 1x

runs:
  BenchmarkBuild:
    BenchmarkBuildSimple:
      description: Simple build
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildMultistage:
      description: Multistage build
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildSecret:
      description: Build with secret
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildRemote:
      description: Build from git context
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildBreaker16:
      description: Build breaker 16x
      count: 3
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildBreaker32:
      description: Build breaker 32x
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildBreaker64:
      description: Build breaker 64x
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildBreaker128:
      description: Build breaker 128x
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkBuildFileTransfer:
      description: Build with substantial file transfer
      count: 4
      metrics:
        duration:
          description: Time (s)
          chart: boxplot

  BenchmarkDaemon:
    BenchmarkDaemonVersion:
      description: Run buildkitd --version
      count: 8
      metrics:
        duration:
          description: Time (s)
          chart: boxplot
    BenchmarkDaemonSize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true

  BenchmarkPackage:
    BenchmarkPackageSize:
      description: Package size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
          chart: bar
          average: true
