defaults:
  count: 3
  benchtime: 1s

runs:
  BenchmarkBinary:
    BenchmarkBinaryVersion:
      description: Daemon binary version
      benchtime: 5s
      metrics:
        duration:
          description: Time (ns)
    BenchmarkBinarySize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
