defaults:
  count: 3
  benchtime: 1s

runs:
  BenchmarkBinary:
    BenchmarkBinaryVersion:
      description: Run --version
      benchtime: 2s
      metrics:
        duration:
          description: Time (ms)
    BenchmarkBinarySize:
      description: Daemon binary size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
    BenchmarkPackageSize:
      description: Package size
      count: 1
      metrics:
        bytes:
          description: Size (bytes)
