# reusable workflow
name: .test

on:
  workflow_call:
    inputs:
      revisions:
        required: true
        type: string

env:
  SETUP_BUILDX_VERSION: "latest"
  SETUP_BUILDKIT_IMAGE: "moby/buildkit:latest"

jobs:
  init:
    runs-on: ubuntu-24.04
    outputs:
      revisions: ${{ steps.set.outputs.revisions }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set outputs
        id: set
        uses: actions/github-script@v7
        with:
          script: |
            await core.group(`Set revisions matrix`, async () => {
              const revisions = `${{ inputs.revisions }}`.trim().split(/\r?\n/);
              core.info(JSON.stringify(revisions, null, 2));
              core.setOutput('revisions', JSON.stringify(revisions));
            });

  prepare:
    runs-on: ubuntu-24.04
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        revision: ${{ fromJson(needs.init.outputs.revisions) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          targets: tests-base
          set: |
            buildkit-binaries.cache-from=type=gha,scope=buildkit-${{ matrix.revision }}
            buildkit-binaries.cache-to=type=gha,scope=buildkit-${{ matrix.revision }}
