# reusable workflow
name: .test

on:
  workflow_call:
    inputs:
      refs:
        required: true
        type: string

env:
  SETUP_BUILDX_VERSION: "latest"
  SETUP_BUILDKIT_IMAGE: "moby/buildkit:latest"

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Export BuildKit refs and Bake overrides
        uses: actions/github-script@v7
        with:
          script: |
            let buildkitRefs = [];
            let bakeOverrides = [];
            await core.group(`Solve commit from ref`, async () => {
              for (const ref of `${{ inputs.refs }}`.trim().split(/\r?\n/)) {
                let release = undefined;
                if (ref === 'latest') {
                  release = await github.rest.repos.getRelease({
                    owner: 'moby',
                    repo: 'buildkit',
                    release_id: ref,
                  });
                }
                const commit = await github.rest.repos.getCommit({
                  owner: 'moby',
                  repo: 'buildkit',
                  ref: release ? release.data.tag_name : ref,
                });
                if (release) {
                  core.info(`${ref} -> ${release.data.tag_name} -> ${commit.data.sha}`);
                  buildkitRefs.push(release.data.tag_name);
                } else {
                  core.info(`${ref} -> ${commit.data.sha}`);
                  buildkitRefs.push(ref);
                }
                const buildkitRef = release ? release.data.tag_name : ref;
                const bakeTarget = `buildkit-build-${buildkitRef.replace(/[^a-zA-Z0-9_-]+/g, '-')}`;
                bakeOverrides.push(`${bakeTarget}.cache-from=type=gha,scope=buildkit-${commit.data.sha}`);
                bakeOverrides.push(`${bakeTarget}.cache-to=type=gha,scope=buildkit-${commit.data.sha}`);
              }
            });
            await core.group(`Export BUILDKIT_REFS`, async () => {
              core.info(JSON.stringify(buildkitRefs, null, 2));
              core.exportVariable('BUILDKIT_REFS', buildkitRefs.join(','));
            });
            await core.group(`Export BAKE_OVERRIDES`, async () => {
              core.info(JSON.stringify(bakeOverrides, null, 2));
              core.exportVariable('BAKE_OVERRIDES', bakeOverrides.join('\n'));
            });
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug
      -
        name: Build base
        uses: docker/bake-action@v5
        with:
          targets: tests-base
          provenance: false
          set: |
            ${{ env.BAKE_OVERRIDES }}
