# reusable workflow
name: .test

on:
  workflow_call:
    inputs:
      refs:
        required: true
        type: string

env:
  SETUP_BUILDX_VERSION: "latest"
  SETUP_BUILDKIT_IMAGE: "moby/buildkit:latest"

jobs:
  init:
    runs-on: ubuntu-24.04
    outputs:
      includes: ${{ steps.set.outputs.includes }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set outputs
        id: set
        uses: actions/github-script@v7
        with:
          script: |
            let includes = [];
            await core.group(`Solve commit from ref`, async () => {
              for (const ref of `${{ inputs.refs }}`.trim().split(/\r?\n/)) {
                const commit = await github.rest.repos.getCommit({
                  owner: 'moby',
                  repo: 'buildkit',
                  ref: ref,
                });
                core.info(`${ref} -> ${commit.data.sha}`);
                includes.push({
                  ref: ref,
                  commit: commit.data.sha,
                });
              }
            });
            await core.group(`Set includes`, async () => {
              core.info(JSON.stringify(includes, null, 2));
              core.setOutput('includes', JSON.stringify(includes ?? []));
            });

  prepare:
    runs-on: ubuntu-24.04
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.init.outputs.includes) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug
      -
        name: Build ${{ matrix.ref }}
        uses: docker/bake-action@v5
        with:
          targets: tests-base
          set: |
            buildkit-binaries.cache-from=type=gha,scope=buildkit-${{ matrix.commit }}
            buildkit-binaries.cache-to=type=gha,scope=buildkit-${{ matrix.commit }}
        env:
          BUILDKIT_REF: ${{ matrix.commit }}
