name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

env:
  GO_VERSION: 1.22
  SETUP_BUILDX_VERSION: latest
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest
  CANDIDATES_REFS: master
  CANDIDATES_LAST_DAYS: 7
  CANDIDATES_LAST_RELEASES: 3

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      includes: ${{ steps.set.outputs.includes }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: List candidates
        run: |
          go run -mod=vendor ./cmd/refcandidates \
            --refs ${{ env.CANDIDATES_REFS }} \
            --last-days ${{ env.CANDIDATES_LAST_DAYS }} \
            --last-releases ${{ env.CANDIDATES_LAST_RELEASES }} \
            --output ./bin/candidates.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set outputs
        id: set
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('./bin/candidates.json', 'utf8'));
            let includes = [];
            for (const [key, value] of Object.entries(data.refs)) {
              includes.push({name: key, ref: key, commit: value});
            }
            for (const [key, value] of Object.entries(data.releases)) {
              includes.push({name: key, ref: key, commit: value});
            }
            for (const [key, value] of Object.entries(data.commits)) {
              includes.push({name: key, ref: value, commit: value});
            }
            core.info(JSON.stringify(includes, null, 2));
            core.setOutput('includes', JSON.stringify(includes ?? []));

  test:
    runs-on: ubuntu-24.04
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.includes) }}
    env:
      TEST_FLAGS: -v --timeout=30m
      TEST_IMAGE_BUILD: 0
      TEST_IMAGE_ID: buildkit-bench
      BUILDKIT_RUN_COUNT: 3
    steps:
      -
        name: Export BuildKit ref for ${{ matrix.name }}
        uses: actions/github-script@v7
        with:
          script: |
            const ref = `${{ matrix.ref }}`;
            core.info(`BUILDKIT_REF=${ref}`);
            core.exportVariable('BUILDKIT_REF', ref);
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug
      -
        name: Build test image
        uses: docker/bake-action@v5
        with:
          targets: tests
          set: |
            *.output=type=docker,name=${{ env.TEST_IMAGE_ID }}
      -
        name: Test
        run: |
          ./hack/test
      -
        name: Result
        run: |
          jq . ./bin/gotestoutput.json
