name: gc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 3 * * 6' # every Saturday at 3:00 UTC
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/gc.yml
  pull_request:
    paths:
      - .github/workflows/gc.yml

env:
  WEBSITE_PUBLIC_PATH: /buildkit-bench/

jobs:
  gc:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: bin/gh-pages
      -
        name: Garbage collect old results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const resultDir = './bin/gh-pages/result';
            const results = fs.readdirSync(resultDir).filter(d => {
              return fs.statSync(path.join(resultDir, d)).isDirectory();
            });

            const resultsByDate = results.reduce((acc, dir) => {
              const date = dir.split('-')[0];
              if (!acc[date]) {
                acc[date] = [];
              }
              acc[date].push(dir);
              return acc;
            }, {});

            Object.keys(resultsByDate).forEach(date => {
              const dirs = resultsByDate[date];
              const keepDirs = [];
              const removeDirs = [];
              dirs.forEach(dir => {
                const envFilePath = path.join(resultDir, dir, 'env.txt');
                if (fs.existsSync(envFilePath)) {
                  const envContent = fs.readFileSync(envFilePath, 'utf8');
                  if (envContent.includes('GITHUB_EVENT_NAME=schedule')) {
                    keepDirs.push(dir);
                    return;
                  }
                }
                removeDirs.push(dir);
              });

              removeDirs.sort().reverse();

              keepDirs.push(...removeDirs.slice(0, 3));

              removeDirs.slice(3).forEach(dir => {
                const dirPath = path.join(resultDir, dir);
                fs.rmSync(dirPath, { recursive: true, force: true });
                core.info(`Removed ${dirPath}`);
              });
            });
      -
        name: Move and list results
        run: |
          mv ./bin/gh-pages/result ./website/public/
          tree -nph ./website/public/result
      -
        name: Build website
        uses: docker/bake-action@v5
        with:
          targets: website
          provenance: false
      -
        name: Publish
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./bin/website
          jekyll: false
          dry_run: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
